syntax = "proto3";

package hipstershop;

option go_package = "mtp-grpc-bridge/genproto;hipstershop";

message Empty {}

message CartItem {
  string product_id = 1;
  int32 quantity = 2;
}

message Money {
  string currency_code = 1;
  int64 units = 2;
  int32 nanos = 3;
}

message Address {
  string street_address = 1;
  string city = 2;
  string state = 3;
  string country = 4;
  int32 zip_code = 5;
}

message GetQuoteRequest {
  Address address = 1;
  repeated CartItem items = 2;
}

message GetQuoteResponse {
  Money cost_usd = 1;
}

message ShipOrderRequest {
  Address address = 1;
  repeated CartItem items = 2;
}

message ShipOrderResponse {
  string tracking_id = 1;
}

service ShippingService {
  rpc GetQuote(GetQuoteRequest) returns (GetQuoteResponse) {}
  rpc ShipOrder(ShipOrderRequest) returns (ShipOrderResponse) {}
}

message GetSupportedCurrenciesResponse {
  repeated string currency_codes = 1;
}

message CurrencyConversionRequest {
  Money from = 1;
  string to_code = 2;
}

service CurrencyService {
  rpc GetSupportedCurrencies(Empty) returns (GetSupportedCurrenciesResponse) {}
  rpc Convert(CurrencyConversionRequest) returns (Money) {}
}

message OrderItem {
  CartItem item = 1;
  Money cost = 2;
}

message OrderResult {
  string order_id = 1;
  string shipping_tracking_id = 2;
  Money shipping_cost = 3;
  Address shipping_address = 4;
  repeated OrderItem items = 5;
}

message SendOrderConfirmationRequest {
  string email = 1;
  OrderResult order = 2;
}

service EmailService {
  rpc SendOrderConfirmation(SendOrderConfirmationRequest) returns (Empty) {}
}

message AdRequest {
  repeated string context_keys = 1;
}

message Ad {
  string redirect_url = 1;
  string text = 2;
}

message AdResponse {
  repeated Ad ads = 1;
}

service AdService {
  rpc GetAds(AdRequest) returns (AdResponse) {}
}
