apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-bridge
  labels:
    app: shipping-bridge
    role: grpc-bridge
    mtp.service: shippingservice
    mtp.backend: faas
spec:
  replicas: 0
  selector:
    matchLabels:
      app: shipping-bridge
      role: grpc-bridge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shipping-bridge
        role: grpc-bridge
        mtp.service: shippingservice
        mtp.backend: faas
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      containers:
      - name: bridge
        image: localhost:30500/shipping-bridge:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE
          value: shipping
        - name: FUNCTION_URL
          value: http://gateway.openfaas.svc.cluster.local:8080/function/shipping
        ports:
        - name: grpc
          containerPort: 50051
        - name: metrics
          containerPort: 9091
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
